services:
  - type: web
    name: cron-system
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: CRON_SECRET
        generateValue: true
      - key: RENDER_URL
        fromService:
          type: web
          name: cron-system
          property: host
      - key: LOG_SINK_URL
        sync: false
      - key: LOG_SINK_TYPE
        value: discord
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BACKUP_DEST
        sync: false
    healthCheckPath: /health